### ISSUE TITLE
Show correct licence

### ISSUE THREAD

**Issue by Zegnat** [indieweb/verify-me#3]
Nice to see my code merged into this (at e10e1126396f3137e756ef865030852668951472), and to see it back on the Chrome Web Store! I might have a go and repackage for AMO too, but no promises.

**However** my code is all licensed under the MIT licence. This is compatible with the Apache-2.0 licence used here, but that doesn’t mean the MIT licence can just be ignored. I have been a big proponent of putting IndieWeb projects in the Public Domain (or licences close to it, such as [0BSD](https://spdx.org/licenses/0BSD.html)), and would be willing to relicense all of my code to such a licence if we can decide to move this repo away from Apache-2.0.

If – for whatever reason – it is important to keep the sidefiles in this repository licensed under Apache-2.0, I ask for a block comment to be added above my code to clarify its MIT licensing.

**Comment by kevinmarks** [comment]
I'm happy for you to change the license as you see fit, as it is now pretty
much all your code. I chose Apache over MIT by institutional preference
rather than licence text.
