### ISSUE TITLE
Also use <link rel="me" href="http..."/>

### ISSUE THREAD

**Issue by mro** [indieweb/verify-me#4]
Hi @kevinmarks-b, currently only (visible, html) `a` links are honoured.

Would you mind adding `<link rel="me" href="http..."/>` also?

P.S.: Motivation: I do a (opinionated) Atom-feed microblog with client-side xslt->html. And there is no `<a>` in source there. https://l.mro.name/

**Comment by Zegnat** [comment]
Where would you expect the check mark icon to show up for `<link>` elements?

**Comment by mro** [comment]
When testing a back-link with https://indiewebify.me/validate-rel-me/?url=https%3A%2F%2Ftry.gogs.io%2Fissue-5008 it says

> …
> https://l.mro.name/o/p/ does not link back
> …

when in fact it does. The above test-website uses `verify-me`, doesn't it?

**Comment by Zegnat** [comment]
> The above test-website uses `verify-me`, doesn't it?

It does not! Woops!

This repository holds the source code for a browser extension that will go over a page and check `rel="me"` links, and then put a visual check mark symbol behind them. that’s why I asked where you expected the icon to show up.

Seems like a miscommunication somewhere. Let me know if you were thinking of the browser extension anyway. If not, I’ll probably close this issue in about a week’s time 😄 (Unless you close it first.)

**Comment by mro** [comment]
yes, sorry, I got this wrong. I thought this here is sort of the heavy lifting behind the scenes of above mentioned validation service website. Not a browser extension.

I apologise for wasting your time, immediately close this issue (here) and would be grateful for a pointer, however.

**Comment by Zegnat** [comment]
> I apologise for wasting your time, immediately close this issue (here) and would be grateful for a pointer, however.

It is no trouble at all! No time wasted.

[Indiewebify.me](https://github.com/indieweb/indiewebify-me) [calls on `relMeLinks()`](https://github.com/indieweb/indiewebify-me/blob/07d0240fbf7fc9fc2a1990dd9c566d5b3472eedf/web/index.php#L172), which comes courtesy of [the indieweb/rel-me](https://github.com/indieweb/rel-me) package, which uses [the php-mf2 parser](https://github.com/microformats/php-mf2) to [extract all rel-me URLs](https://github.com/indieweb/rel-me/blob/6a6c9de41f5b18ef99243340a365949f2c47df0e/RelMe.php#L163-L165).

Just leading to the fact that the current php-mf2 is unable to parse your website, and it has 2 issues filed on the matter.
